services:
  broker:
    build:
      context: ./req-rep
      dockerfile: Dockerfile_broker
    container_name: broker
    ports:
      - "5555:5555"
      - "5556:5556"

  proxy:
      build:
        context: ./proxy
        dockerfile: Dockerfile
      container_name: proxy
      command: ["python", "-u", "proxy.py"]
      ports:
        - "5557:5557"
        - "5558:5558"

  servidor:
    build:
      context: ./req-rep
      dockerfile: Dockerfile_servidor
    container_name: servidor
    volumes:
      - ./messages.log:/app/messages.log
      - ./usuarios.json:/app/usuarios.json
      - ./canais.json:/app/canais.json
    depends_on:
      - broker
      - proxy

  bot-go:
    build:
      context: ./proxy
      dockerfile: Dockerfile_botgo
    depends_on:
      - servidor
    deploy:
      replicas: 2

  cliente-js:
    build:
      context: ./req-rep
      dockerfile: Dockerfile_cliente
    stdin_open: true 
    tty: true
    depends_on:
      - servidor