# Usa uma imagem oficial do Node.js
FROM node:18-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o package.json para instalar as dependências primeiro (cache do Docker)
COPY package.json .

# Roda o comando de instalação DENTRO do container
RUN npm install

# Copia o resto do código do cliente
COPY cliente.js .

# Comando padrão para rodar quando o container iniciar
CMD ["node", "cliente.js"]